"""empty message

Revision ID: 13042826746f
Revises: None
Create Date: 2020-03-05 18:34:16.822012

"""

# revision identifiers, used by Alembic.
revision = '13042826746f'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hunter_email', sa.String(), nullable=True),
    sa.Column('target_email', sa.String(), nullable=True),
    sa.Column('time_created', sa.String(), nullable=True),
    sa.Column('time_ended', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('number_of_elims', sa.Integer(), nullable=True),
    sa.Column('time_of_last_elim', sa.String(), nullable=True),
    sa.Column('time_eliminated', sa.String(), nullable=True),
    sa.Column('is_immune', sa.Integer(), nullable=True),
    sa.Column('time_immunity_activated', sa.String(), nullable=True),
    sa.Column('immunity_duration', sa.Integer(), nullable=True),
    sa.Column('time_created', sa.String(), nullable=True, extend_existing=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('matches')
    # ### end Alembic commands ###
