"""empty message

Revision ID: 4a209681f16e
Revises: None
Create Date: 2020-03-05 13:14:45.000831

"""

# revision identifiers, used by Alembic.
revision = '4a209681f16e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DailyMenu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('menu', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('number_of_elims', sa.Integer(), nullable=True),
    sa.Column('time_of_last_elim', sa.Integer(), nullable=True),
    sa.Column('time_eliminated', sa.Integer(), nullable=True),
    sa.Column('is_immune', sa.Integer(), nullable=True),
    sa.Column('time_immunity_activated', sa.Integer(), nullable=True),
    sa.Column('immunity_duration', sa.Integer(), nullable=True),
    sa.Column('time_created', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('DailyMenu')
    # ### end Alembic commands ###
