"""empty message

Revision ID: 50c281a16d35
Revises: fd6237d3409f
Create Date: 2020-03-07 17:09:06.823792

"""

# revision identifiers, used by Alembic.
revision = '50c281a16d35'
down_revision = 'fd6237d3409f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('num_revives', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'num_revives')
    # ### end Alembic commands ###
