"""empty message

Revision ID: 58b696b32a31
Revises: 5f97dafba070
Create Date: 2020-04-21 18:24:11.018600

"""

# revision identifiers, used by Alembic.
revision = '58b696b32a31'
down_revision = '5f97dafba070'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('announcement', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('announcements')
    # ### end Alembic commands ###
