"""empty message

Revision ID: 5f97dafba070
Revises: 059d7bac9a0d
Create Date: 2020-03-11 21:59:56.684821

"""

# revision identifiers, used by Alembic.
revision = '5f97dafba070'
down_revision = '059d7bac9a0d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('rank', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'rank')
    # ### end Alembic commands ###
