"""empty message

Revision ID: 8a96c6e44bab
Revises: ce53456d75f7
Create Date: 2020-03-05 15:26:42.256448

"""

# revision identifiers, used by Alembic.
revision = '8a96c6e44bab'
down_revision = 'ce53456d75f7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_id')
    # ### end Alembic commands ###
