"""empty message

Revision ID: aa8796aa932e
Revises: None
Create Date: 2020-03-09 16:03:59.541379

"""

# revision identifiers, used by Alembic.
revision = 'aa8796aa932e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('codes_found', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'codes_found')
    # ### end Alembic commands ###
