"""empty message

Revision ID: bd539efd71f4
Revises: 58b696b32a31
Create Date: 2020-04-21 18:25:13.355839

"""

# revision identifiers, used by Alembic.
revision = 'bd539efd71f4'
down_revision = '58b696b32a31'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('announcements', sa.Column('announcement_content', sa.String(), nullable=True))
    op.add_column('announcements', sa.Column('announcement_title', sa.String(), nullable=True))
    op.drop_column('announcements', 'announcement')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('announcements', sa.Column('announcement', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('announcements', 'announcement_title')
    op.drop_column('announcements', 'announcement_content')
    # ### end Alembic commands ###
