"""empty message

Revision ID: ce53456d75f7
Revises: 4a209681f16e
Create Date: 2020-03-05 14:55:12.745156

"""

# revision identifiers, used by Alembic.
revision = 'ce53456d75f7'
down_revision = '4a209681f16e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hunter_email', sa.String(), nullable=True),
    sa.Column('target_email', sa.String(), nullable=True),
    sa.Column('time_created', sa.Integer(), nullable=True),
    sa.Column('time_ended', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matches')
    # ### end Alembic commands ###
