"""empty message

Revision ID: fd6237d3409f
Revises: 13042826746f
Create Date: 2020-03-07 16:44:42.005071

"""

# revision identifiers, used by Alembic.
revision = 'fd6237d3409f'
down_revision = '13042826746f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pause',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_paused', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pause')
    # ### end Alembic commands ###
